# Package definition for k6

package_name: k6
github_repo: grafana/k6
artifact_format: tar.gz
description: "A modern load-testing tool for testing the performance and reliability of APIs and services, scriptable in JavaScript."
license: AGPL-3.0

# Build for all Debian suites and all supported architectures.
